services:
  bot-telegram:
    build: .
    container_name: ${CONTAINER_NAME:-bot_prod}
    restart: always
    ports:
      - "${HOST_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # Esta URL le dice al bot dónde está la base de datos
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db_gastos
    deploy:
      resources:
        limits:
          memory: 400M # Bajamos un poco el límite del bot para darle aire a la DB

  db_gastos:
    image: postgres:15-alpine # La versión 'alpine' es mucho más liviana (ideal para Oracle)
    container_name: ${DB_CONTAINER_NAME:-postgres_prod}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 300M # Postgres para uso personal corre perfecto con 300MB

volumes:
  pg_data: # Aquí es donde se guardarán tus gastos físicamente